image:
  repository: jspc/kafka-to-redisearch
  tag: 0.5.0
  pullPolicy: IfNotPresent

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

kafka:
  bootstrapServers: content-kafka:9092
  topic: content

redis:
  master: content-redis-master:6379
  index: content
